version: '3'

services:
  pwang_security_db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: pwang_security_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ../pwang-mysql:/var/lib/mysql
      - ../pwang-mysql-conf:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - pwang
    restart: always

  hyper_real_api-api:
    build:
      context: ./java
    container_name: pwang-api
    ports:
      - "8080:8080"
    depends_on:
      - pwang_security_db
    networks:
      - pwang
    restart: always

networks:
  pwang:
    driver: bridge
